FROM nvcr.io/qc69jvmznzxy/llm_nim/nano@sha256:7244f1580de69cddbf172fea2611b556fb0ccb00b1bbb338df5cce97deed0785

COPY components/src/dynamo/frontend/prepost.py /usr/local/lib/python3.12/dist-packages/dynamo/frontend/prepost.py

RUN python3 -m py_compile /usr/local/lib/python3.12/dist-packages/dynamo/frontend/prepost.py \
 && echo "bce52c442bc39a4a0fd88b7c9734b79c0148991a869c599637ca299fb4271f60  /usr/local/lib/python3.12/dist-packages/dynamo/frontend/prepost.py" \
    | sha256sum --check --strict

LABEL org.opencontainers.image.revision="c0b65919460b6b93342948777571940b0cda5848" \
      com.nvidia.dynamo.source.revision="c0b65919460b6b93342948777571940b0cda5848" \
      ai.nvidia.nano.dynamo.base-digest="sha256:7244f1580de69cddbf172fea2611b556fb0ccb00b1bbb338df5cce97deed0785" \
      ai.nvidia.nano.dynamo.dynamo-commit="c0b65919460b6b93342948777571940b0cda5848" \
      ai.nvidia.nano.dynamo.version="1.3.0" \
      ai.nvidia.nano.dynamo.vllm-version="0.26.0+cu129"
